-- ⚠️ DEPRECATED — moved to /supabase/schema.sql
--
-- This file used to contain a parallel schema definition that diverged
-- from supabase/schema.sql. Both have now been consolidated.
--
--   • Fresh install ............ run `supabase/schema.sql`
--   • Existing database ........ run `supabase/migrations/0002_consolidate.sql`
--
-- Keep this file as a redirect note so old links don't 404.
