import { createClient, createServiceClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import type { User, AdminStaff } from '@/lib/types'

// Get current authenticated user profile
export async function getCurrentUser(): Promise<User | null> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null

  const { data } = await supabase
    .from('users')
    .select('*')
    .eq('id', user!.id)
    .single()

  return data as User | null
}

// Require user auth — redirect to login if not logged in
export async function requireUser(): Promise<User> {
  const user = await getCurrentUser()
  if (!user) redirect('/login')
  return user
}

// Get current admin staff
export async function getCurrentAdmin(): Promise<AdminStaff | null> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null

  const adminSupabase = createServiceClient()
  const { data } = await adminSupabase
    .from('admin_staff')
    .select('*')
    .eq('auth_user_id', user!.id)
    .eq('is_active', true)
    .single()

  return data as AdminStaff | null
}

// Require admin — redirect if not admin
export async function requireAdmin(): Promise<AdminStaff> {
  const admin = await getCurrentAdmin()
  if (!admin) redirect('/login')
  return admin
}

// Check if admin has permission for a channel
export function hasChannelAccess(admin: AdminStaff, channel: 'ONLINE' | 'ONSITE'): boolean {
  if (admin.role === 'SUPER_ADMIN') return true
  return admin.channel_access.includes(channel)
}

// Create or update user profile after first login
export async function upsertUserProfile(
  authUserId: string,
  data: { phone?: string; email?: string; full_name?: string }
) {
  const supabase = createServiceClient()

  // Check if exists
  const { data: existing } = await supabase
    .from('users')
    .select('id')
    .eq('id', authUserId)
    .single()

  if (!existing) {
    // Create new profile
    const { error } = await supabase.from('users').insert({
      id: authUserId,
      phone: data.phone || null,
      email: data.email || null,
      full_name: data.full_name || null,
      member_id: '', // will be auto-generated by trigger
    })
    if (error) throw error
  }
}